# Generated by Django 2.1.2 on 2018-10-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.IntegerField(default=0, help_text='Выберите категорию верхнего уровня'),
        ),
    ]
