# Generated by Django 2.1.2 on 2018-10-06 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_auto_20181006_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Выберите категорию верхнего уровня', null=True, on_delete=django.db.models.deletion.CASCADE, to='toys.Category'),
        ),
    ]
