# Generated by Django 2.1.2 on 2018-10-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0004_auto_20181006_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Укажите стоимость изделия', max_digits=15),
        ),
    ]
