# Generated by Django 2.1.2 on 2018-10-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0005_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
