# Generated by Django 2.1.2 on 2018-10-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0006_auto_20181006_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите наименование свойства', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Укажите описание свойства')),
                ('enabled', models.BooleanField(help_text='Активность')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
