# Generated by Django 2.1.2 on 2018-10-06 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0007_productproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPropertyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.CharField(help_text='Укажите знаичение свойства', max_length=255)),
                ('product', models.ForeignKey(help_text='Выберите изделие', on_delete=django.db.models.deletion.CASCADE, to='toys.Product')),
                ('property', models.ForeignKey(help_text='Выберите свойство', on_delete=django.db.models.deletion.CASCADE, to='toys.ProductProperty')),
            ],
        ),
    ]
