# Generated by Django 2.1.2 on 2018-10-07 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0009_category_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveSmallIntegerField(help_text='Укажите порядок следования изображения')),
                ('description', models.CharField(help_text='Укажите описание изображения', max_length=255)),
                ('photo', models.ImageField(help_text='Выберите файл с изображением', null=True, upload_to='product')),
                ('product', models.ForeignKey(help_text='Выберите изделие', on_delete=django.db.models.deletion.CASCADE, to='toys.Product')),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(help_text='Выберите файл с изображением', null=True, upload_to='category'),
        ),
        migrations.AlterField(
            model_name='productpropertyvalue',
            name='val',
            field=models.CharField(help_text='Укажите значение свойства', max_length=255),
        ),
    ]
