# Generated by Django 2.1.2 on 2018-10-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0010_auto_20181007_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='description',
            field=models.CharField(help_text='Укажите описание изображения', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='photo',
            field=models.ImageField(default=2, help_text='Выберите файл с изображением', upload_to='product'),
            preserve_default=False,
        ),
    ]
