# Generated by Django 2.1.2 on 2018-10-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0011_auto_20181007_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='description',
            field=models.CharField(blank=True, help_text='Укажите описание изображения', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='sort',
            field=models.PositiveSmallIntegerField(default=0, help_text='Укажите порядок следования изображения'),
        ),
    ]
