# Generated by Django 2.1.2 on 2018-10-13 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0012_auto_20181007_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите наименование конкурса', max_length=255)),
                ('dt_start', models.DateField(help_text='Укажите дату начала конкурса')),
                ('dt_end', models.DateField(help_text='Укажите дату окончания конкурса', null=True)),
                ('description', models.TextField(help_text='Укажите описание конкурса', null=True)),
                ('category', models.TextField(help_text='Укажите категорию конкурса для изделия')),
                ('product', models.ForeignKey(help_text='Выберите изделие', on_delete=django.db.models.deletion.CASCADE, to='toys.Product')),
            ],
            options={
                'ordering': ['dt_start'],
            },
        ),
        migrations.CreateModel(
            name='ContestImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveSmallIntegerField(default=0, help_text='Укажите порядок следования изображения')),
                ('description', models.CharField(blank=True, help_text='Укажите описание изображения', max_length=255, null=True)),
                ('photo', models.ImageField(help_text='Выберите файл с изображением', upload_to='product')),
                ('contest', models.ForeignKey(help_text='Выберите изделие', on_delete=django.db.models.deletion.CASCADE, to='toys.Contest')),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
    ]
