# Generated by Django 2.1.2 on 2018-10-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0013_contest_contestimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='category',
            field=models.TextField(blank=True, help_text='Укажите категорию конкурса для изделия', null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(blank=True, help_text='Укажите описание конкурса', null=True),
        ),
        migrations.AlterField(
            model_name='contestimage',
            name='photo',
            field=models.ImageField(help_text='Выберите файл с изображением', upload_to='contest'),
        ),
    ]
