# Generated by Django 2.1.2 on 2018-10-13 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0014_auto_20181013_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_create', models.DateTimeField(help_text='Укажите дату добавления отзыва')),
                ('user_name', models.CharField(help_text='Укажите имя пользователя', max_length=255)),
                ('description', models.CharField(help_text='Укажите текст отзыва', max_length=255)),
                ('user_email', models.EmailField(blank=True, help_text='Укажите e-mail пользователя', max_length=254, null=True)),
                ('dt_moderation', models.DateTimeField(blank=True, help_text='Укажите дату модерации отзыва', null=True)),
                ('enabled', models.BooleanField(help_text='Публиковать')),
                ('product', models.ForeignKey(help_text='Выберите изделие', on_delete=django.db.models.deletion.CASCADE, to='toys.Product')),
            ],
            options={
                'ordering': ['dt_create'],
            },
        ),
    ]
