# Generated by Django 2.1.2 on 2018-10-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0015_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, help_text='Укажите оценку'),
        ),
    ]
