# Generated by Django 2.1.2 on 2018-10-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0017_auto_20181013_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
